name: Release Workflow
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build ESctl binaries
        run: |
          make build-cross
          make dist
      - name: Get Version
        id: get_version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v\([0-9.]*\)/\1/p')"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _dist/esctl-v${{ steps.title.outputs.title }}-amd64-darwin.tar.gz
            _dist/esctl-v${{ steps.title.outputs.title }}-arm64-darwin.tar.gz
            _dist/esctl-v${{ steps.title.outputs.title }}-amd64-linux.tar.gz
            _dist/esctl-v${{ steps.title.outputs.title }}-arm64-linux.tar.gz
            _dist/esctl-v${{ steps.title.outputs.title }}-amd64-windows.tar.gz
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          title: ESctl v${{ steps.get_version.outputs.version }}
          body_path: release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
