name: Release Workflow

on:
  create:
    tags:
      - v*
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build ESctl binaries
      run: |
        make build-cross
        make dist

    - name: Upload binaries
      id: create_release
      uses: actions/create-release@v1
      with:
        files: |
          _dist/esctl-linux-amd64.tar.gz
          _dist/esctl-darwin-amd64.tar.gz
          _dist/esctl-windows-amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
